### ISSUE TITLE
unroll doesn't work with where

### ISSUE THREAD

**Issue by Datseris** [cstjean/Unrolled.jl#2]
I am opening this after https://discourse.julialang.org/t/unrolled-jl-problems-with-where-keyword/9715

Me and @lhupe are working on some (quite big) performance gains on a package that has a container that if unrolled will be very helpful. (what we are trying to do is actually described here: https://discourse.julialang.org/t/is-there-a-way-to-forward-getindex-for-tuples-in-a-type-stable-way/2889/20)

Unfortuantelly we both suck at metaprogramming. Are you willing to guide us through a PR that fixes the `where` issue? (We haven't managed to solve it ourselves yet :D )

**Comment by cstjean** [comment]
Looks like I had already fixed the problem locally, but hadn't pushed it to this repository. Sorry! Could you please try it out `Pkg.checkout("Unrolled")` and see if it fixes the issue for you? Then I can tag a release.

**Comment by lhupe** [comment]
Seems to work now.

**Comment by Datseris** [comment]
Thanks @cstjean !
